app = "pixel-ui"
primary_region = "bom"

[build]
  dockerfile = "packages/server/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1