app = "pixel-ui"
primary_region = "bom"

[build]
image = "talhadevelopes/pixel-ui-server:latest"

[env]
NODE_ENV = "production"
PORT = "4000"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 4_000
min_machines_running = 0
